version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  flaskapp:
    build: ./flaskapp
    environment:
        - OPEN_AI_SECRET_KEY=${OPEN_AI_SECRET_KEY}
        - DB_PROTOCOL=${DB_PROTOCOL}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - DB_IPADDRESS=db
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 5000:5000
    depends_on:
      - db